# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/pisit/Documents/pong-game/final-project/final-project.cache/wt [current_project]
set_property parent.project_path /home/pisit/Documents/pong-game/final-project/final-project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/pisit/Downloads/Compressed/vivado-boards-master/new/board_files} [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo /home/pisit/Documents/pong-game/final-project/final-project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/exec_matrix_compiled.vh
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/exec_zero.vh
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/exec_module.vh
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/temp_wires.vh
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/coremodules.vh
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/core.vh
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/globals.vh
}
read_mem {
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/work/ram.mif
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/punnisa/ping.list
}
read_verilog -library xil_defaultlib {
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/hdl/PS2Receiver.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/address_latch.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/address_mux.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/address_pins.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/alu.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/alu_bit_select.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/alu_control.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/alu_core.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/alu_flags.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/alu_mux_2.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/alu_mux_2z.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/alu_mux_3z.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/alu_mux_4.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/alu_mux_8.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/alu_prep_daa.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/alu_select.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/alu_shifter_core.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/alu_slice.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/hdl/bin2ascii.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/bus_control.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/bus_switch.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/clk_delay.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/new/clock_divider.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/new/clock_generator.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/control_pins_n.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/data_pins.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/data_switch.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/data_switch_mask.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/hdl/debouncer.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/decode_state.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/execute.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/new/hex_to_seven_seg.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/inc_dec.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/inc_dec_2bit.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/interrupts.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/ir.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/new/keyboard_io.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/memory_ifc.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/pin_control.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/pla_decode.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/new/ram.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/new/readBG.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/reg_control.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/reg_file.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/reg_latch.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/resets.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/sequencer.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/new/seven_seg_display.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/hdl/uart_buf_con.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/hdl/uart_tx.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/new/vga.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/new/vga_io.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/imports/z80/z80_top_direct_n.v
  /home/pisit/Documents/pong-game/final-project/final-project.srcs/sources_1/new/system.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/pisit/Documents/pong-game/final-project/final-project.srcs/constrs_1/imports/VivadoProjects/Basys-3-Master.xdc
set_property used_in_implementation false [get_files /home/pisit/Documents/pong-game/final-project/final-project.srcs/constrs_1/imports/VivadoProjects/Basys-3-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top system -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_utilization_synth.rpt -pb system_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
